### ISSUE TITLE
起動スクリプトの作成

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#64]
# タスク内容

AMIの起動処理を記述したスクリプトを作成する。（企画書のSTEP1を達成するものであるため、VAEをデフォルトで用いるが、STEP2で既存手法がデフォルトで使用されるように書き換える）

`scripts/launch.py`に記述する。

[`hydra`](https://hydra.cc)を用いてコマンドライン引数、ハイパーパラメータ、使用するクラスを設定する。
諸々のconfigファイルを作成する必要があるが、ここでは `configs/launch.yaml`のみ取り上げる。
他のconfigファイルは別途のタスクissueをたて、実装する。

### スケッチ
```yaml
# @package _global_

defaults:
  -  _self_
  - interaction: default
  - models: image_vae
  - data_collectors: image
  - trainers: image_vae
  - threads: default

  - paths: default
  - hydra: default
  
  - experiment: null

task_name: "image_encoding_by_vae"
```

```py
import hydra

@hydra.main(version_base=None, config_path="../configs", config_name="launch")
def main(cfg: DictConfig) -> None:
    interaction: Interaction = hydra.utils.instantiate(cfg.interaction)
    models: ModelWrappersDict = hydra.utils.instantiate(cfg.models)
    data_collectors: DataCollectorsDict = hydra.utils.instantiate(cfg.data_collectors)
    trainers: TrainersList = hydra.utils.instantiate(cfg.trainers)
    
    threads = cfg.threads
    inference_thread: InferenceThread = hydra.utils.instantiate(threads.inference, interaction=interaction, data_collectors=data_collectors)
    training_thread: TrainingThread = hydra.utils.instantiate(threads.training, trainers=trainers, model_wrappers=models)
    main_thread: MainThread = hydra.utils.instantiate(threads.main_thread)
    
    attach_shared_object_pool_to_threads(main_thread, inference_thread, training_thread)
    
    inference_thread.start()
    training_thread.start()
    
    main_thread.run() # ここで Blocking 

    inference_thread.join()
    training_thread.join()


if __name__ == "__main__":
    main()
```

### 達成条件

- [ ] `launch.yaml`
- [ ] `launch.py`
- [ ] 実動作確認が行われた。
