### ISSUE TITLE
Image VAE の EncoderとDecoderをインスタンス化するモデル設定ファイル

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#65]
# タスク内容

`hydra`を用いて Image VAE のEncoderとDecoderを持った `ModelWrapersDict`をinstantiateするyamlファイルを作成する。

`configs/models/image_vae.yaml`に記述する。
`hydra.utils.instantiate`で問題無く 呼び出されるかテストする。テストは `tests/config_tests/test_models.py`に記述する。

NOTE: モデルのkeyの名前は`ModelNames`列挙クラスの`IMAGE_ENCODER`, `IMAGE_DECODER`と一致させる。

### スケッチ

image_vae.yaml
```yaml
_target_: ami.models.utils.ModelWrappersDict
image_encoder:
  _target_: ami.models.vae.EncoderWrapper
  default_device: "cuda"
  model:
    _target_: ami.models.vae.Conv2dEncoder
    height: 84
    width: 84
    ... # 引数を指定

image_decoder:
  _target_: ami.models.model_wrapper.ModelWrapper
  default_device: "cuda"
  has_inference: False
  model:
    _target_: ami.models.vae.Conv2dDecoder
    ... # 引数を指定
```

test_models.py
```py
from tests.helpers import PROJECT_ROOT
import hydra
from omegaconf import OmegaConf

def test_image_vae():
    cfg = OmegaConf.load(PROJECT_ROOT / "configs/models/image_vae.yaml")
    hydra.utils.instantiate(cfg)
```
### 達成条件

- [ ] 設定ファイルが記述された。
- [ ] 問題無くinstantiateできる。

### 参考
hydra: https://hydra.cc/docs/intro/
vae: https://github.com/MLShukai/ami/blob/main/ami/models/vae.py
model_wrappers
