### ISSUE TITLE
Threadクラス群をインスタンス化する設定ファイルの作成

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#72]
# タスク内容

#64 を達成するために、`hydra`を用いて MainThread, InferenceThread, TrainingThreadをインスタンス化するyaml 設定ファイルを記述する。

設定ファイルは`configs/threads/default.yaml`に記述する。

単独ではインスタンス化することが不可能であるため、インスタンス化を確認するテストは記述しない（かもしれない。Interaction, DataCollectors, Models, Trainersと一緒にテストする可能性はあり）

### スケッチ

```yaml
main: path.to.MainThread

inference: path.to.InferenceThread

training: path.to.TrainingThread
```

### 達成条件

- [ ] 設定ファイルが記述された
