### ISSUE TITLE
`Trainers`インスタンス化する設定ファイルを記述

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#73]
# タスク内容

`hydra`をを用いて VAE Trainerをインスタンス化するyaml設定ファイルを記述する。マイルストーン STEP1を達成するためのものである。

`configs/trainers/image_vae.yaml`に記述する。

```yaml
_target_: path.to.TrainersList
_args_:
  - _target_: path.to.VAETrainer
    value1: ...
```

### 達成条件

- [ ] 設定ファイルが記述された。
