### ISSUE TITLE
`DataCollectors`をインスタンス化する設定ファイルを記述する

### ISSUE THREAD

**Issue by Geson-anko** [MLShukai/ami#74]
# タスク内容

`hydra`でDataCollector (Data Buffer)をインスタンス化するyaml設定ファイルを記述。`DataCollectorsDict.from_buffers`を用いる。

`configs/data_collectors/image.yaml`に記述する。

```yaml
_target_: path.to.DataCollectorsDict.from_buffers
image_buffer:
  _target_: path.to.RandomDataBuffer
  arg1: ...
```

### 達成条件

- [ ] 設定ファイルが記述された
